# A task to be executed by the role
---
  - name: Print env variables
    shell: echo $PATH
    register: print_result

  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines}}"